version: '2'
services:
  nginx:
    image: nginx:1.12
    container_name: rainbowClient
    ports:
      - 8080:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/app
    links:
      - phpfpm

  phpfpm:
    image: php:7.1-fpm
    container_name: rainbowGenerator
    volumes:
      - .:/var/www/app
    ports:
      - 9000
    links:
      - redis
    depends_on:
      - redis


  redis:
    image: redis
    container_name: rainbowDb
    ports:
      - 6379:6379

